### ISSUE TITLE
can not build it in macos catalina version 10.15.7, Bazel 4.0.0 and xcode 12.4

### ISSUE THREAD

**Issue by lexuanquynh** [larryaasen/bazelbuild_examples#1]
I run your script and get this error throw:
``` swift
ERROR: /private/var/tmp/_bazel_nguyenphuongthao/6b29721cd13f6b1709dacf15de174f80/external/build_bazel_rules_apple/tools/realpath/BUILD:9:14: in _apple_genrule_inner rule @build_bazel_rules_apple//tools/realpath:realpath_genrule:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_nguyenphuongthao/6b29721cd13f6b1709dacf15de174f80/external/build_bazel_apple_support/rules/apple_genrule.bzl", line 78, column 28, in _apple_genrule_impl
		apple_support.run_shell(
	File "/private/var/tmp/_bazel_nguyenphuongthao/6b29721cd13f6b1709dacf15de174f80/external/build_bazel_apple_support/lib/apple_support.bzl", line 326, column 26, in _run_shell
		ctx.actions.run_shell(**_kwargs_for_apple_platform(ctx, **kwargs))
Error in run_shell: 'command' must be of type string. passing a sequence of strings as 'command' is deprecated. To temporarily disable this check, set --incompatible_run_shell_command_string=false.
INFO: Repository com_google_protobuf instantiated at:
  /Users/nguyenphuongthao/coding/ios/bazelbuild_examples/ios/HelloWorld/WORKSPACE:54:25: in <toplevel>
  /private/var/tmp/_bazel_nguyenphuongthao/6b29721cd13f6b1709dacf15de174f80/external/build_bazel_rules_swift/swift/repositories.bzl:88:11: in swift_rules_dependencies
  /private/var/tmp/_bazel_nguyenphuongthao/6b29721cd13f6b1709dacf15de174f80/external/build_bazel_rules_swift/swift/repositories.bzl:32:18: in _maybe
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_nguyenphuongthao/6b29721cd13f6b1709dacf15de174f80/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository com_github_nlohmann_json instantiated at:
  /Users/nguyenphuongthao/coding/ios/bazelbuild_examples/ios/HelloWorld/WORKSPACE:54:25: in <toplevel>
  /private/var/tmp/_bazel_nguyenphuongthao/6b29721cd13f6b1709dacf15de174f80/external/build_bazel_rules_swift/swift/repositories.bzl:79:11: in swift_rules_dependencies
  /private/var/tmp/_bazel_nguyenphuongthao/6b29721cd13f6b1709dacf15de174f80/external/build_bazel_rules_swift/swift/repositories.bzl:32:18: in _maybe
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_nguyenphuongthao/6b29721cd13f6b1709dacf15de174f80/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//:HelloWorld' failed; build aborted: Analysis of target '@build_bazel_rules_apple//tools/realpath:realpath_genrule' failed
INFO: Elapsed time: 26.856s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (38 packages loaded, 440 targets configured)
make: *** [build_app] Error 1
```

**Comment by lexuanquynh** [comment]
I try to use a way [by link](https://github.com/google/mediapipe/issues/1551)
but It's not work. please help me.

**Comment by larryaasen** [comment]
@lexuanquynh Sorry, I am not sure how to help you.
